INSERT INTO personal (fornamn, efternamn, roll) 
VALUES  ('Henry', 'Quisth', 'Manager'),
        ('Ann', 'Holmgren', 'Cleaner'),
        ('Gun', 'Åström', 'Manager'),
        ('Björn', 'Pehrson', 'Cleaner'),
        ('Carina', 'Svensson', 'Manager'),
        ('Henrik', 'Bergqvist', 'Manager'),
        ('Harry', 'Höglund', 'Receptionist'),
        ('Anders', 'Hansson', 'Cleaner'),
        ('Sten', 'Andreasson', 'Receptionist'),
        ('Stefan', 'Fjäll', 'Receptionist'),
        ('Viktoria', 'Frisk', 'Cleaner'),
        ('Hans', 'Lindgren', 'Cleaner');
